### ISSUE TITLE
Not connecting to the linked database

### ISSUE THREAD

**Issue by MiquelAdell** [docker-library/wordpress#120]
Steps to reproduce:

1. create a new docker-compose.yml
2. paste the example from the website and save:

    wordpress:
      image: wordpress
      links:
        - db:mysql
      ports:
        - 8080:80

    db:
      image: mariadb
      environment:
        MYSQL_ROOT_PASSWORD: example

3. $ docker-compose up

4. wait a little

5. go to the exposed web front end

Error establishing a database connection

I created a more detailed explanation (plus full log) here:
http://stackoverflow.com/questions/34746853/docker-wordpress-container-cant-connect-to-database-container

EDIT: I just tried using:
image: wordpress:4.4

and the exmaple did work so it seems to be a bug introduced between 4.4 and 4.4.1

**Comment by tianon** [comment]
Can you try doing "docker-compose pull" and giving it another shot?

**Comment by MiquelAdell** [comment]
Yep it works!

Thanks.
I'll close the issue.

**Comment by MiquelAdell** [comment]
Sorry to keep asking on a closed issue but I assumed that you did update the image and that what solved was that pull did pull a new image but I've just checked the repo and seen that there haven't been new pushes for 3 days…

What did docker-compose pull do?
In what was that different than removing the image and making docker-compose up with "wordress:latest"?

I'd like to know for next time.

Thanks!

**Comment by yosifkit** [comment]
If that fixed it, then `docker-compose pull` grabbed the new image from the hub.  Doing an `rm` and `up` would have only used the image you had locally, unless you also did `docker rmi wordpress` so that it would have to `pull` the image. `docker-compose rm` only deletes containers and not images.

It was a bug with the line endings and was fixed in this repo in https://github.com/docker-library/wordpress/pull/117, but was not added to the build server until https://github.com/docker-library/official-images/pull/1328 was merged. The `docker-library/official-images` repo is what controls the builds and pushes to the hub.

**Comment by jamieshiz** [comment]
I have tried removing my local `wordpress` image and running `docker-compose pull` but I am still experiencing this issue. Here is my docker-compose.yml - 
services:
  wordpress:
    image: wordpress
    volumes:
      - ./src:/var/www/html
    links:
      - wp_db:mysql
    ports:
      - "8080:80"
  wp_db:
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: some-secure-pw
      MYSQL_USER: my-user
      MYSQL_PASSWORD: my-password
      MYSQL_DATABASE: my-db

**Comment by yosifkit** [comment]
Since you have the `services` section you'll also need a `version: '2'` and have to give the password, user, and database to WordPress too.

```yaml
version: '2'
services:
  wordpress:
    image: wordpress
    volumes:
      - ./src:/var/www/html
    environment:
      WORDPRESS_DB_HOST: wp_db
      WORDPRESS_DB_USER: my-user
      WORDPRESS_DB_PASSWORD: my-password
      WORDPRESS_DB_NAME: my-db
    ports:
      - "8080:80"
  wp_db:
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: some-secure-pw
      MYSQL_USER: my-user
      MYSQL_PASSWORD: my-password
      MYSQL_DATABASE: my-db
```

**Comment by ayushpadia** [comment]
Sorry to keep asking on a closed issue but my problem is not resolved till now. My script is:

version: '3.7'

services:
  # Database
  db:
    image: mysql
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    ports:
        - '8200:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8201:80'
    environment:
        PMA_HOST: db
        PMA_PASSWORD: password
        MYSQL_ROOT_PASSWORD: password
    networks:
      - wpsite
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress
    ports:
      - '8202:80'
    restart: always
    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data:

**Comment by yosifkit** [comment]
@ayushpadia, most likely you need to give mysql longer to come up and when using `mysql:latest` you are probably running into https://github.com/docker-library/mysql/issues/409.

For further debugging, you might want to try [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).

**Comment by rmindo** [comment]
@ayushpadia Try this.

kill and remove the previous running container
`docker down`

in **docker-compose.yml** Replace all properties under **db** service with the code below.
` db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    restart: always
    environment:
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: password`

The reason why wordpress service can't connect is that you changed the default port of the database without telling the ** WORDPRESS_DB_HOST** for the new port so its should be like this **db:8200**. or you can leave the default port by not defining it.

**Comment by deepdev1** [comment]
I'm trying to have two separate Wordpress stacks (sites) on the same machine. First site started and working flawlessly. I couldn't get the second site working, stuck with `Error establishing a database connection`. 
Here's the second site's `docker-compose.yml`:
```
version: "3.3"
    
services:
  db2:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    container_name: wp2-db
    restart: always
    ports:
      - "4306:3306"
    environment:
      MYSQL_DB_NAME: wordpress2
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

    
  wordpress2:
    depends_on:
      - db2
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "8001:80"
    container_name: wp2
    restart: always
    environment:
      WORDPRESS_DB_NAME: wordpress2
      WORDPRESS_DB_HOST: db2:4306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
```

I can only think of the change of `mysql` port causing the problem as @rmindo mentioned. Yet I've defined it properly for wordpress to recognize in `WORDPRESS_DB_HOST`. Any input is much appreciated. Thank you.

**Comment by yosifkit** [comment]
@deepdev1, you can't change the port that other containers access each other with `ports`; that is only the port that is exposed to the whole external network (i.e. on the host or other hosts via the host IP). So, `WORDPRESS_DB_HOST: db2:4306` needs to be `WORDPRESS_DB_HOST: db2` or `WORDPRESS_DB_HOST: db2:3306`.

**Comment by deepdev1** [comment]
@yosifkit, thank you. It's such a key and important information. 
Also, I'm late to realize that the second `mysql` container though listening on `port 3306` can co-exist with the another one, since the service is now listening on a different internal IP address (potentially on a different network) specific to it.

Unfortunately, still `Error establishing a database connection`. I couldn't notice any database connection error in the logs of `wordpress` container. Any observation? Thank you.
