### ISSUE TITLE
PHP 7.4

### ISSUE THREAD

**Issue by candrews** [docker-library/wordpress#453]
PHP 7.4 has been released. Can you please provide Wordpress docker images for it?

Thank you!

**Comment by tianon** [comment]
Done in https://github.com/docker-library/wordpress/pull/454 :+1:

**Comment by candrews** [comment]
This doesn't seem to be pushed to Docker Hub (yet?)
https://hub.docker.com/_/wordpress/

When/how will that happen?

Thanks again!

**Comment by yosifkit** [comment]
https://github.com/docker-library/wordpress#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet

So, here https://github.com/docker-library/official-images/pull/7076

**Comment by cdbattags** [comment]
I tried pulling `wordpress:5.3-php7.4-apache` and `wordpress:5.3-php7.3-apache` and it seems I'm still getting PHP 7.2?

Anyone have any idea?

Full Dockerfile:

```
FROM wordpress:5.3-php7.4-apache

COPY --chown=www-data:www-data wp-content/plugins /var/www/html/wp-content/plugins

COPY docker-entrypoint.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/docker-entrypoint.sh

RUN mkdir /var/www/html/wp-uploads
```
